# Generated by Django 5.0.2 on 2024-02-26 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('bookstore', '0001_initial'), ('bookstore', '0002_remove_author_birth_date_remove_book_published')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.author')),
            ],
        ),
    ]
